mikepenz/FastAdapter

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/mikepenz/fastadapter/app/CheckBoxSampleActivity.java
- app/src/main/java/com/mikepenz/fastadapter/app/RadioButtonSampleActivity.java
- app/src/main/java/com/mikepenz/fastadapter/app/SampleActivity.java
- app/src/main/java/com/mikepenz/fastadapter/app/items/CheckBoxSampleItem.java
- app/src/main/java/com/mikepenz/fastadapter/app/items/RadioButtonSampleItem.java
- app/src/main/res/layout/checkbox_sample_item.xml
- app/src/main/res/layout/radiobutton_sample_item.xml
- app/src/main/res/values/ids.xml
- app/src/main/res/values/strings.xml
> new samples:

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/mikepenz/fastadapter/app/SampleActivity.java
- app/src/main/java/com/mikepenz/fastadapter/app/SortActivity.java
- app/src/main/res/layout/activity_sort.xml
- app/src/main/res/values/strings.xml
As @Rainer-Lang requested in #51 I have made a simple sample for sorting.
I am not quite sure if this is the best way to do it (See my comments) but it is something :)
> Add a simple sample for sorting

- .travis.yml
- library/build.gradle
I have setup travis CI for us. Here is my fork's build: https://travis-ci.org/shubhamchaudhary/FastAdapter/builds/117635711
@mikepenz Please turn on the build here: https://docs.travis-ci.com/user/getting-started/#To-get-started-with-Travis-CI%3A
> travis-ci setup

- README.md
How-to's for various functionalities
> Added tutorials

- app/src/main/java/com/mikepenz/fastadapter/app/SortActivity.java
- app/src/main/java/com/mikepenz/fastadapter/app/items/ExpandableItem.java
- library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/HeaderHelper.java
- library/src/main/java/com/mikepenz/fastadapter/helpers/ClickListenerHelper.java
- library/src/main/java/com/mikepenz/fastadapter/utils/AdapterUtil.java
- library/src/main/java/com/mikepenz/fastadapter/utils/IdDistributor.java
> little things

- app/src/main/java/com/mikepenz/fastadapter/app/generic/GenericIconItem.java
- app/src/main/java/com/mikepenz/fastadapter/app/items/CheckBoxSampleItem.java
- app/src/main/java/com/mikepenz/fastadapter/app/items/ExpandableItem.java
- app/src/main/java/com/mikepenz/fastadapter/app/items/IconItem.java
- app/src/main/java/com/mikepenz/fastadapter/app/items/ImageItem.java
- app/src/main/java/com/mikepenz/fastadapter/app/items/LetterItem.java
- app/src/main/java/com/mikepenz/fastadapter/app/items/RadioButtonSampleItem.java
- app/src/main/java/com/mikepenz/fastadapter/app/items/RealmSampleUserItem.java
- app/src/main/java/com/mikepenz/fastadapter/app/items/SampleItem.java
- app/src/main/java/com/mikepenz/fastadapter/app/items/SimpleImageItem.java
- app/src/main/java/com/mikepenz/fastadapter/app/items/SwipeableItem.java
- library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/items/ProgressItem.java
- library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/items/SingleLineItem.java
- library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/items/ThreeLineItem.java
- library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/items/TwoLineItem.java
- library/src/main/java/com/mikepenz/fastadapter/FastAdapter.java
- library/src/main/java/com/mikepenz/fastadapter/IItem.java
- library/src/main/java/com/mikepenz/fastadapter/items/AbstractItem.java
Add the unbind method to the item interface. Unbind will call when the item got recycled from the recyclerview.
> [WIP][Feature] unbind

- library/src/main/java/com/mikepenz/fastadapter/FastAdapter.java
- library/src/main/java/com/mikepenz/fastadapter/ISelectionListener.java
This one was missing in the last pull request
> Generic ISelectionListener

- library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/IExtendedDraggable.java
- library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/utilities/DragDropUtil.java
- library/src/main/java/com/mikepenz/fastadapter/items/AbstractItem.java
must now be called manually in bindView of the IExtendedDraggable item
> Moved the custom drag handle setup to a utility class

- library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/utilities/SubItemUtil.java
* added getAllItems functions in addition to the count functions and adjusted the count functions to use this getAllItems functions...
functions works, regardless of collapsed or expanded state...
> SubItemUtil adjusted

- app/src/main/java/com/mikepenz/fastadapter/app/CheckBoxSampleActivity.java
- app/src/main/java/com/mikepenz/fastadapter/app/items/CheckBoxSampleItem.java
- build.gradle
- library/src/main/java/com/mikepenz/fastadapter/FastAdapter.java
- library/src/main/java/com/mikepenz/fastadapter/helpers/ClickListenerHelper.java
- library/src/main/java/com/mikepenz/fastadapter/listeners/ClickEventHook.java
- library/src/main/java/com/mikepenz/fastadapter/listeners/CustomEventHook.java
- library/src/main/java/com/mikepenz/fastadapter/listeners/EventHook.java
- library/src/main/java/com/mikepenz/fastadapter/listeners/LongClickEventHook.java
- library/src/main/java/com/mikepenz/fastadapter/listeners/TouchEventHook.java
* implement new EventHook logic, to simplify listeners on views inside the item
> Better and more flexible ClickListenerHelper, with direct FastAdapter integration

- library/src/main/java/com/mikepenz/fastadapter/commons/utils/FastAdapterUIUtils.java
Update the getSelectableBackground from FastAdapterUtils to use the parameter animate.
> Only animate selectable background if we want to

- README.md
- app/src/main/java/com/mikepenz/fastadapter/app/ExpandableMultiselectDeleteSampleActivity.java
- library-core/src/main/java/com/mikepenz/fastadapter/AbstractAdapter.java
- library-core/src/main/java/com/mikepenz/fastadapter/FastAdapter.java
- library-core/src/main/java/com/mikepenz/fastadapter/IAdapter.java
- library-core/src/main/java/com/mikepenz/fastadapter/IItem.java
- library-core/src/main/java/com/mikepenz/fastadapter/ISubItem.java
- library-core/src/main/java/com/mikepenz/fastadapter/adapters/FooterAdapter.java
- library-core/src/main/java/com/mikepenz/fastadapter/adapters/HeaderAdapter.java
- library-core/src/main/java/com/mikepenz/fastadapter/adapters/ItemAdapter.java
- library-extensions-firebase/src/main/java/com/mikepenz/fastadapter_extensions/firebase/FirebaseItemAdapter.java
- library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/scroll/EndlessRecyclerOnTopScrollListener.java
- library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/utilities/SubItemUtil.java
- library/src/main/java/com/mikepenz/fastadapter/commons/adapters/AbstractWrapAdapter.java
- library/src/main/java/com/mikepenz/fastadapter/commons/adapters/FastItemAdapter.java
Fix some typos and a link in the readme
> Typo Fixes

- library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/UndoHelper.java
withSnackBar(Snackbar, String), getSnackBar(), and remove(Set<Integer>)
> added some convenience methods

- library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/UndoHelper.java
Add `Item` generic to UndoListener in UndoHelper field/constructor
> Add Item generic to UndoHelper.UndoListener

- library-core/src/main/java/com/mikepenz/fastadapter/IGenericItem.java
> Fix return value of method withModel in IGenericItem

- Gemfile
- _config.yml
In light of #474 , if you've previously auto generated the pages and would like to keep it in sync with the Read me for future builds, you may consider using the following. Especially since you won't want to invest more time in customizing the gh page, it may make sense to do the following since users might choose to read the website.
> Jekyll configs for automatic github pages

- README.md
Fixed a typo and moved away from deprecated method in README
> Move away from deprecated method

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- library-extensions-expandable/build.gradle
- library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/items/SingleLineItem.java
- library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/items/ThreeLineItem.java
- library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/items/TwoLineItem.java
> Set avatar gone instead of invisible when is missing

- app/src/main/java/com/mikepenz/fastadapter/app/AdvancedSampleActivity.java
- app/src/main/java/com/mikepenz/fastadapter/app/CheckBoxSampleActivity.java
- app/src/main/java/com/mikepenz/fastadapter/app/ExpandableMultiselectDeleteSampleActivity.java
- app/src/main/java/com/mikepenz/fastadapter/app/ExpandableSampleActivity.java
- app/src/main/java/com/mikepenz/fastadapter/app/IconGridActivity.java
- app/src/main/java/com/mikepenz/fastadapter/app/ImageListActivity.java
- app/src/main/java/com/mikepenz/fastadapter/app/ModelItemActivity.java
- app/src/main/java/com/mikepenz/fastadapter/app/MultiTypeModelItemActivity.java
- app/src/main/java/com/mikepenz/fastadapter/app/MultiselectSampleActivity.java
- app/src/main/java/com/mikepenz/fastadapter/app/RadioButtonSampleActivity.java
- app/src/main/java/com/mikepenz/fastadapter/app/RealmActivity.java
- app/src/main/java/com/mikepenz/fastadapter/app/SampleActivity.java
- app/src/main/java/com/mikepenz/fastadapter/app/SimpleItemListActivity.java
- app/src/main/java/com/mikepenz/fastadapter/app/StickyHeaderSampleActivity.java
Same as #507 , but on v3 and on all files. I am still new on Github, sorry for the duplicate.
> Fix typo (Bundel -> Bundle)

- app/src/main/java/com/mikepenz/fastadapter/app/items/SimpleItem.java
- app/src/main/java/com/mikepenz/fastadapter/app/items/SwipeableItem.java
- app/src/main/java/com/mikepenz/fastadapter/app/items/expandable/SimpleSubItem.java
- library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/drag/IDraggable.java
- library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/drag/IExtendedDraggable.java
- library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/drag/SimpleDragCallback.java
- library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/swipe/ISwipeable.java
- library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/swipe/SimpleSwipeCallback.java
- library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/utilities/DragDropUtil.java
* move IDraggable to extensions.../drag/*
* move ISwipeable to extensions.../swipe/*
* move IExtendedDraggable to extensions.../drag/*
> [V3] Move extension interfaces to extension module

- library-core/src/main/java/com/mikepenz/fastadapter/FastAdapter.java
- library-core/src/main/java/com/mikepenz/fastadapter/ITypeInstanceCache.java
- library-core/src/main/java/com/mikepenz/fastadapter/utils/DefaultTypeInstanceCache.java
* Its now possible to implement an own caching solution for the type instances
> [V3] Feature/shared type instance cache

- app/src/main/java/com/mikepenz/fastadapter/app/DiffUtilActivity.java
- library/src/main/java/com/mikepenz/fastadapter/commons/utils/FastAdapterDiffUtil.java
* implement `DiffUtil` adjustment by @FabianTerhorst to fix some potential issues with the diff update
* properly update list and notify rv
* adjust sample to use new ctor
* FIX https://github.com/mikepenz/FastAdapter/issues/589
> DiffUtil fix

- app/src/main/java/com/mikepenz/fastadapter/app/DiffUtilActivity.java
- library/src/main/java/com/mikepenz/fastadapter/commons/utils/FastAdapterDiffUtil.java
- library/src/test/java/com/mikepenz/fastadapter/FastAdapterDiffUtilTest.java
- library/src/test/java/com/mikepenz/fastadapter/TestDataGenerator.java
- library/src/test/java/com/mikepenz/fastadapter/TestItem.java
> [TEST] Test new DiffUtil

- README.md
As ItemFilter is now moved to ItemAdapter so updated the documents
> Fixed Readme about ItemFilter

- library-core/src/main/java/com/mikepenz/fastadapter/FastAdapter.kt
* add the "out" keyword to the generic item type for eventHooks
> [v4] "out" keyword for EventHooks

- library-core/src/main/java/com/mikepenz/fastadapter/FastAdapter.kt
- library-core/src/main/java/com/mikepenz/fastadapter/extensions/ExtensionsFactories.kt
> Reified functions

- library-extensions-diff/src/main/java/com/mikepenz/fastadapter/diff/FastAdapterDiffUtil.kt
General comments
* With Kotlin, I believe using default parameters is more favourable to introducing a bunch of helper functions with reduced arguments. Named variables also helps with evolution if the order changes. With that said, I also think boolean variables may be better off in front of object variables like the callback
* In general, you rarely need to use `ArrayList`. There's `toMutableList()` and `toList()` instead, which better shows the intention. The underlying code will still create an arraylist.
* Is checking for an empty list necessary before clear?
* For set operators, it looks [like this](https://kotlinlang.org/docs/reference/operator-overloading.html#indexed). I don't think this is what you really want with your function.
> Simplify some parts of the diff util

- library-core/src/main/java/com/mikepenz/fastadapter/extensions/ExtensionFactory.kt
- library-core/src/main/java/com/mikepenz/fastadapter/extensions/ExtensionsFactories.kt
- library-core/src/main/java/com/mikepenz/fastadapter/select/SelectExtensionFactory.kt
- library-extensions-expandable/src/main/java/com/mikepenz/fastadapter/expandable/ExpandableExtensionFactory.kt
Resolves #779
Just a proof of concept. This is naturally a breaking change as well
Note: Code style doesn't match. Will wait for code formatter merge
> Force class match in extension factory

- app/src/main/java/com/mikepenz/fastadapter/app/AdvancedSampleActivity.kt
- library-core/src/main/java/com/mikepenz/fastadapter/IAdapter.kt
- library-core/src/main/java/com/mikepenz/fastadapter/IAdapterExtension.kt
- library-core/src/main/java/com/mikepenz/fastadapter/IItem.kt
* introduce some more generic typealiases to simplify generic usage
> Generic TypeAliases

- README.md
Otherwise `${...}` doesn't work
> Use double quotes for gradle dependencies

- app/src/main/java/com/mikepenz/fastadapter/app/AdvancedSampleActivity.kt
- app/src/main/java/com/mikepenz/fastadapter/app/EndlessScrollListActivity.kt
- app/src/main/java/com/mikepenz/fastadapter/app/ExpandableMultiselectDeleteSampleActivity.kt
- app/src/main/java/com/mikepenz/fastadapter/app/ExpandableSampleActivity.kt
- library-core/src/main/java/com/mikepenz/fastadapter/IAdapter.kt
- library-core/src/main/java/com/mikepenz/fastadapter/IAdapterExtension.kt
- library-core/src/main/java/com/mikepenz/fastadapter/adapters/ItemAdapter.kt
- library-core/src/main/java/com/mikepenz/fastadapter/adapters/ModelAdapter.kt
- library-core/src/main/java/com/mikepenz/fastadapter/extensions/ExtensionFactory.kt
- library-core/src/main/java/com/mikepenz/fastadapter/extensions/ExtensionsFactories.kt
- library-extensions-expandable/src/main/java/com/mikepenz/fastadapter/expandable/ExpandableExtension.kt
- library-extensions-expandable/src/main/java/com/mikepenz/fastadapter/expandable/ExpandableExtensionFactory.kt
- library-extensions-utils/src/main/java/com/mikepenz/fastadapter/adapters/FastItemAdapter.kt
Replaced `IItem<out RecyclerView.ViewHolder>` everywhere and updated imports
> Use `GenericItem` everywhere

- app/src/main/java/com/mikepenz/fastadapter/app/adapters/StickyHeaderAdapter.kt
- library-core/src/main/java/com/mikepenz/fastadapter/FastAdapter.kt
- library-core/src/main/java/com/mikepenz/fastadapter/IClickable.kt
- library-core/src/main/java/com/mikepenz/fastadapter/adapters/ItemFilter.kt
- library-core/src/main/java/com/mikepenz/fastadapter/listeners/CustomEventHook.kt
- library-core/src/main/java/com/mikepenz/fastadapter/listeners/OnBindViewHolderListenerImpl.kt
- library-core/src/main/java/com/mikepenz/fastadapter/select/SelectExtension.kt
General code cleanup.
For anything I have questions about, I will make a comment
> WIP: Misc kotlin updates

- app/src/main/java/com/mikepenz/fastadapter/app/MultiTypeModelItemActivity.kt
- app/src/main/java/com/mikepenz/fastadapter/app/items/ImageItem.kt
- app/src/main/java/com/mikepenz/fastadapter/app/items/SimpleImageItem.kt
- library-core/src/main/java/com/mikepenz/fastadapter/adapters/ItemFilter.kt
- library-core/src/main/java/com/mikepenz/fastadapter/adapters/ModelAdapter.kt
- library-core/src/main/java/com/mikepenz/fastadapter/utils/DefaultItemListImpl.kt
- library-extensions-expandable/src/main/java/com/mikepenz/fastadapter/expandable/ExpandableExtension.kt
- library-extensions-expandable/src/main/java/com/mikepenz/fastadapter/utils/SubItemUtil.kt
- library-extensions-scroll/src/main/java/com/mikepenz/fastadapter/scroll/EndlessScrollHelper.kt
- library-extensions-utils/src/main/java/com/mikepenz/fastadapter/adapters/AbstractWrapAdapter.kt
Kotlin misc will just be a series of changes I see as I go through code. You can review/merge it at any time
> Kotlin misc

- library-extensions-expandable/src/main/java/com/mikepenz/fastadapter/expandable/ExpandableExtension.kt
* change property visibility to internal as noted
> Mark isExpanded as internal

- library-extensions-paged/src/main/java/com/mikepenz/fastadapter/paged/PagedModelAdapter.kt
* allow passing null to the PagedModelAdapter.submitList
* FIX https://github.com/mikepenz/FastAdapter/issues/834
> Fix #834 (Can't pass null to submitList)

- app/src/main/java/com/mikepenz/fastadapter/app/PagedActivity.kt
- app/src/main/java/com/mikepenz/fastadapter/app/items/SimpleImageItem.kt
My own example of using the new placeholderInterceptor parameter
> Usage of placeholderInterceptor in sample app

- library-core/src/main/java/com/mikepenz/fastadapter/FastAdapter.kt
- library-extensions-expandable/src/test/java/com/mikepenz/fastadapter/ExpandableFastAdapterTest.kt
- library-extensions-ui/src/main/java/com/mikepenz/fastadapter/ui/dialog/FastAdapterBottomSheetDialog.kt
- library-extensions-ui/src/main/java/com/mikepenz/fastadapter/ui/dialog/FastAdapterDialog.kt
* remove the generic type specification for the adapter
* FIX https://github.com/mikepenz/FastAdapter/issues/838
> [V5] Fix issue #838

- library-core/src/main/java/com/mikepenz/fastadapter/AbstractAdapter.kt
- library-core/src/main/java/com/mikepenz/fastadapter/FastAdapter.kt
- library-core/src/main/java/com/mikepenz/fastadapter/IItemList.kt
- library-core/src/main/java/com/mikepenz/fastadapter/adapters/ModelAdapter.kt
- library-core/src/main/java/com/mikepenz/fastadapter/utils/DefaultItemList.kt
- allow to mark adapters as active / inactive
- inactive adapters will not be visible in the list
> [V5] Disable-able adapters

- library-extensions-swipe/src/main/java/com/mikepenz/fastadapter/swipe/SimpleSwipeCallback.kt
> -fix(#866): drawables with ratio different than 1:1 (swipe)

- library-extensions-diff/src/main/java/com/mikepenz/fastadapter/diff/FastAdapterDiffUtil.kt
- split apart functions in diff util to allow a more modular usage
- RELATED https://github.com/mikepenz/FastAdapter/issues/893
> Split apart FastAdapterDiffUtil functions

- library-extensions-utils/src/main/java/com/mikepenz/fastadapter/swipe_drag/SimpleSwipeDragCallback.kt
One was nullable and the other not; now they're both aligned ;-)
> Fix tiny inconsistency between helper and main class arguments

- .github/workflows/ci.yml
Disable release builds for tags, instead only run for custom dispatch
This is a try to require a passphrase to decrypt secrets
> [CI] Disable release builds for tags

- .github/config/configuration.json
- .github/workflows/ci.yml
- README.md
- introduce automatic changelog generation for releases
- ignore pre-releases for full releases
- custom config with other section
> Automatic changelog generation for releases

- app/src/main/java/com/mikepenz/fastadapter/app/SwipeDrawerListActivity.kt
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- update to kotlin 1.4.20
- update to iconics 5.1.1
- update materialDrawer 8.2.0
- update aboutLibs 8.6.2
- gradle build tools 4.1.1
> Dependency updates | Kotlin 1.4.20

- README.md
- app/build.gradle
- app/src/main/java/com/mikepenz/fastadapter/app/MopubAdsActivity.kt
- app/src/main/java/com/mikepenz/fastadapter/app/SortActivity.kt
- app/src/main/java/com/mikepenz/fastadapter/app/StickyHeaderMopubAdsActivity.kt
- app/src/main/java/com/mikepenz/fastadapter/app/items/SimpleImageItem.kt
- fastadapter-extensions-binding/build.gradle
- fastadapter-extensions-diff/build.gradle
- fastadapter-extensions-drag/build.gradle
- fastadapter-extensions-expandable/build.gradle
- fastadapter-extensions-paged/build.gradle
- fastadapter-extensions-scroll/build.gradle
- fastadapter-extensions-swipe/build.gradle
- fastadapter-extensions-ui/build.gradle
- fastadapter-extensions-utils/build.gradle
- fastadapter/build.gradle
- gradle-release.gradle
- gradle.properties
- update project to properly provide transitive dependencies 
- update gradle-release.gradle script to ensure dependencies as compile
- cleanup duplicated dependency specifications
- remove butterknife 
- cleanup sample app gradle some more
> Update project to properly have transitive dependencies as compile

- .github/workflows/ci.yml
- README.md
- app/build.gradle
- app/src/main/java/com/mikepenz/fastadapter/app/MopubAdsActivity.kt
- app/src/main/java/com/mikepenz/fastadapter/app/SortActivity.kt
- app/src/main/java/com/mikepenz/fastadapter/app/StickyHeaderMopubAdsActivity.kt
- app/src/main/java/com/mikepenz/fastadapter/app/items/SimpleImageItem.kt
- build.gradle
- fastadapter-extensions-binding/build.gradle
- fastadapter-extensions-diff/build.gradle
- fastadapter-extensions-drag/build.gradle
- fastadapter-extensions-expandable/build.gradle
- fastadapter-extensions-paged/build.gradle
- fastadapter-extensions-scroll/build.gradle
- fastadapter-extensions-swipe/build.gradle
- fastadapter-extensions-ui/build.gradle
- fastadapter-extensions-utils/build.gradle
- fastadapter/build.gradle
- gradle-release.gradle
- gradle.properties
> dev -> main

- DEV/default-detekt-config.yml
- app/build.gradle
- build.gradle
- fastadapter-extensions-diff/build.gradle
- fastadapter-extensions-expandable/build.gradle
- fastadapter-extensions-scroll/src/main/java/com/mikepenz/fastadapter/scroll/EndlessScrollHelper.kt
- fastadapter/build.gradle
- gradle/wrapper/gradle-wrapper.properties
- upgrade environment and all dependencies to their latest stable
- upgrade room to 2.4.0-alpha04 for Apple Silicon chip
> Upgrade dependencies / environment

- fastadapter-extensions-swipe/src/main/java/com/mikepenz/fastadapter/swipe/Extensions.kt
- ensure dirs flag is properly updated
- FIX https://github.com/mikepenz/FastAdapter/issues/1012
> Fix `dirs` flag is not properly updated in some cases

- app/src/main/java/com/mikepenz/fastadapter/app/ExpandableMultiselectDeleteSampleActivity.kt
- app/src/main/java/com/mikepenz/fastadapter/app/MultiselectSampleActivity.kt
- fastadapter-extensions-utils/src/main/java/com/mikepenz/fastadapter/helpers/UndoHelper.kt
- adjust API to provide the [Snackbar] to the [UndoHelper]
- this is a breaking API change. Previous API was not functional anymore
- FIX https://github.com/mikepenz/FastAdapter/issues/1019
- Thanks to @daniyelp
> Enhanced `Snackbar` API in `UndoHelper`

- app/src/main/java/com/mikepenz/fastadapter/app/items/expandable/SimpleSubExpandableItem.kt
https://user-images.githubusercontent.com/2678680/143481711-97800692-b4a0-44a4-9050-c855f82837e7.mp4
> Update expandable example with new payload feature
