- app/src/main/AndroidManifest.xml
- app/src/main/java/com/mikepenz/fastadapter/app/SampleActivity.java
- app/src/main/java/com/mikepenz/fastadapter/app/SwipeListActivity.java
- app/src/main/java/com/mikepenz/fastadapter/app/items/SwipeableItem.java
- app/src/main/java/com/mikepenz/fastadapter/app/swipe/SimpleSwipeCallback.java
- app/src/main/java/com/mikepenz/fastadapter/app/swipe/SimpleSwipeDragCallback.java
- app/src/main/res/layout/swipeable_item.xml
- app/src/main/res/values/ids.xml
- app/src/main/res/values/strings.xml
Swipe remove with in-place undo and "leave-behind" from enhancement issue #43 
This replaces PR #44 which accidently rebased master into the branch.
See discussion in #43 
This adds swipe in two directions to the sample app in a separate activity, while preserving ability to drag (optional). Different swipe directions can be specified with optionally different actions along with icons and background color. Undo of said actions is also possible and included in the example. The undo option is also in place and times out of 3s in the example. A future update could let that stay until scrolled like in the gmail app.
Example app:
> Swipe remove with in-place undo and "leave-behind" from enhancement issue #43 

- library-extensions/src/main/java/android/support/v7/widget/com_mikepenz_fastadapter_extensions_scroll.java
- library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/scroll/EndlessRecyclerOnScrollListener.java
- library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/scroll/EndlessScrollHelper.java
I would like to add `EndlessScrollHelper`
- An extension of `EndlessRecyclerOnScrollListener` that allows a more granular implementation of `onLoadMore()`.
- Providing an easy construct for running an asynchronous loader to load the new items and automatically handling the delivery of those stuff to the main thread.
It also comes with a utility that delivers the new items to an `IItemAdapter` or `GenericItemAdapter`.
I'm not sure if I'm convinced with the naming so feel free to criticize! ;)
> A powerful API for endless scrolling

- library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/HeaderHelper.java
Check if the list is empty before trying to apply the headerhelper to avoid index exception
> Solve index exception in HeaderHelper

- library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/ActionModeHelper.java
Following features are added:
* ActionMode now shows selection count
* added method to recheck ActionMode on demand (for updating after the selection count has changed manually or to restore action mode after screen rotation)
* added the possibility to provide a custom TitleProvider (this can show something like "x of y", "x/y"  or similar instead of the simple language independent count as the default implementation does
> ActionModeHelper improved

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/mikepenz/fastadapter/app/AdvancedSampleActivity.java
- app/src/main/java/com/mikepenz/fastadapter/app/ExpandableMultiselectDeleteSampleActivity.java
- app/src/main/java/com/mikepenz/fastadapter/app/ExpandableSampleActivity.java
- app/src/main/java/com/mikepenz/fastadapter/app/IconGridActivity.java
- app/src/main/java/com/mikepenz/fastadapter/app/MultiselectSampleActivity.java
- app/src/main/java/com/mikepenz/fastadapter/app/SampleActivity.java
- app/src/main/java/com/mikepenz/fastadapter/app/SimpleItemListActivity.java
- app/src/main/java/com/mikepenz/fastadapter/app/items/ExpandableItem.java
- app/src/main/java/com/mikepenz/fastadapter/app/items/HeaderSelectionItem.java
- app/src/main/java/com/mikepenz/fastadapter/app/items/IconItem.java
- app/src/main/java/com/mikepenz/fastadapter/app/items/SampleItem.java
- app/src/main/res/values/strings.xml
- library-extensions-firebase/src/main/java/com/mikepenz/fastadapter_extensions/firebase/FirebaseItemAdapter.java
- library-extensions-realm/src/main/java/io/realm/RealmItemAdapter.java
- library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/ActionModeHelper.java
- library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/RangeSelectorHelper.java
- library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/utilities/SubItemUtils.java
- library/src/main/java/com/mikepenz/fastadapter/AbstractAdapter.java
- library/src/main/java/com/mikepenz/fastadapter/FastAdapter.java
- library/src/main/java/com/mikepenz/fastadapter/IExpandable.java
- library/src/main/java/com/mikepenz/fastadapter/IItemAdapter.java
- library/src/main/java/com/mikepenz/fastadapter/ISelectionListener.java
- library/src/main/java/com/mikepenz/fastadapter/ISubItem.java
- library/src/main/java/com/mikepenz/fastadapter/adapters/FastItemAdapter.java
- library/src/main/java/com/mikepenz/fastadapter/adapters/ItemAdapter.java
- library/src/test/java/com/mikepenz/fastadapter/TestItem.java
Following was added:
**SubItems**
* `SubItemUtils` (count, selection, delete functions that respect collapsed sub items)
* Demo activity added that shows those new functions in action
* Adjusted other examples to fulfill the new two way relation between `IExpandable` and `ISubItem`
**Others**
* `RangeSelectorHelper` - it tracks long pressed items and allows to select all items between the two consecutive long pressed items
* added ability to reset and recreate the map of all possible types for the `RecyclerView` (necessary, if don't want to change your items but you have items that are able to render different item types depending on a user selected theme for example)
* `ISelectionListener` - this allows to be notified about selection changes (regardless of where they come from!)
> SubItems and more

- library/src/main/java/com/mikepenz/fastadapter/IExtendedDraggable.java
- library/src/main/java/com/mikepenz/fastadapter/items/AbstractItem.java
Usage is like following:
* implement the new `IExtendedDraggable` interface in your item
* setup the `SimpleDragCallback` and disable the drag enabled (this disables the drag on long press, we don't want that, we want to let the item itself decide)
* pass the drag helper to the items
> Drag&Drop improved

- library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/scroll/EndlessRecyclerOnTopScrollListener.java
Hi Mike,
With this `EndlessRecyclerOnTopScrollListener` users may load more data while scrolling top on their `RecyclerView`s.
**Features**
- Automatically finding good visible threshold
- `onLoadMore()` when need to load more data
- `onNoMore()` when there's no data to be loaded, user may wants to send a request to the server for asking more data (not required for loading data from local DB)
**Sample**
```java
RecyclerView rv = (RecyclerView) findViewById(R.id.rv);
LinearLayoutManager layoutManager = new LinearLayoutManager(getApplicationContext());
final FastItemAdapter<SampleItem> adapter = new FastItemAdapter<>();
rv.setHasFixedSize(true);
layoutManager.setStackFromEnd(true);
rv.setLayoutManager(layoutManager);
rv.setAdapter(adapter);
for (int i = 0; i < 100; i++) {
adapter.add(new …
```
> new EndlessRecyclerOnTopScrollListener

- library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/utilities/SubItemUtil.java
* added a small function to notify the adapter about changed sub items via identifiers which will update the selected items directly and only if they are currently visible in the adapter
Additionally, I wanted to throw in following:
Nearly everywhere, you are not handling sub items in your default adapter implementations. Why do you have a `notifyAdapterSubItemsChanged`? I think this is a little confusing and should be part of the `SubItemUtil` as well...
> added a notifier function for sub items

- library-core/src/main/java/com/mikepenz/fastadapter/FastAdapter.java
Data structures like `HashMap`, or even worse `TreeMap` or `TreeSet` consume way more memory than array-based structures usually recommended for Android like `SparseArray` or the new [`ArraySet`](https://developer.android.com/reference/android/support/v4/util/ArraySet.html). Lookup performance differences are negligible for up to hundreds of items which make array-based structures a perfect fit to store adapters metadata in `FastAdapter`.
This commit only impacts internal data structures of `FastAdapter` and does not change the public API.
**Optimizations in detail:**
- `LinkedList` should be banned. If you need a queue, `ArrayDeque` or `CircularArray` should be used. Here we don't even need that, so a simple `ArrayList` does the same job perfectly.
- `ArrayMap<Integer, X>` can be …
> Use more memory-efficient data structures in core FastAdapter

- library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/ActionModeHelper.java
- library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/RangeSelectorHelper.java
- library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/utilities/SubItemUtil.java
* action mode helper can be resetted => needed, if you retain the helper on rotation and don't want to leak the activity
* range selector and SubItemUtil supports a payload for a more effective notifying of the adapter
I saw, that the `FastAdapter.select()` does not yet support payloads for the select functions, I think it should though...
> Small improvements (SubItemUtil, RangeSelector, ActionModeHelper)

- library-core/src/main/java/com/mikepenz/fastadapter/FastAdapter.java
I can't think of better idea to solve #360 other than this one-line fix, or to loop until exception thrown at `item = getItem(i);` instead of `i < size` (python style).
> Fix: failed withSavedInstanceState if withPositionBasedStateManagement(false)

- library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/UndoHelper.java
- setCallback is deprecated
- set ActionMode always, in order to replace the existing message each time remove() is called
> UndoHelper fixes

- library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/utilities/DragDropUtil.java
The order of exchanging items was not working with grids, now it's working with grids as well
> DragDropUtil onMove fixed

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/mikepenz/fastadapter/app/DiffUtilActivity.java
- app/src/main/java/com/mikepenz/fastadapter/app/SampleActivity.java
- app/src/main/res/menu/refresh.xml
- app/src/main/res/values/strings.xml
- library/src/main/java/com/mikepenz/fastadapter/commons/utils/FastAdapterDiffUtil.java
`FastAdapterDiffUtil` contains new method `calculateDiff` to allow calculate diff on background thread and later dispatch result to recycler on main thread using `set.`
Change is backward compatible.
Example included.
> Allow DiffUtil to calculate on background thread

- library-extensions-expandable/src/main/java/com/mikepenz/fastadapter/expandable/ExpandableExtension.java
The expandable extension has to use the internal add to prevent the intercept from being triggered.
> [V3] Bug/expandable no intercept

- app/src/main/java/com/mikepenz/fastadapter/app/items/SimpleItem.java
- library-core/src/main/java/com/mikepenz/fastadapter/FastAdapter.java
- library-core/src/main/java/com/mikepenz/fastadapter/listeners/OnBindViewHolderListenerImpl.java
* provide a new FastAdapter.ViewHolder which allows the viewHolder to do the heavy work (the item can be even more dumb)  
* if FastAdapter.ViewHolder is used, the callbacks on the item are not used
> [V3] Clever ViewHolder

- app/src/main/java/com/mikepenz/fastadapter/app/ExpandableSampleActivity.java
- library-extensions-expandable/src/main/java/com/mikepenz/fastadapter/expandable/ExpandableExtension.java
First thanks for the great library! We are using it at [Transportr](/grote/Transportr) and playing a bit, I found the following bug when collapsing a sub-item with only one sub-sub-item: The sub-sub-item will still remain in place instead of being hidden by collapsing the sub-item.
The fix should be as simply as adding an `=` sign to count the sub-items properly. I didn't build nor test the change, but should work as is.
> Fix collapse bug in expandable extention

- app/src/main/java/com/mikepenz/fastadapter/app/ExpandableSampleActivity.java
- library-extensions-expandable/src/main/java/com/mikepenz/fastadapter/expandable/ExpandableExtension.java
I've continued playing with the library at [Transportr](/grote/Transportr), this time with the `withOnlyOneExpandedItem` function. In the current version, *all* other expanded items will be collapsed, including the possible (expanded) parent item, so at the end, nothing stays expanded.
Same thing as in the other pull request: First commit extends the sample app to see the bug inside `ExpandableSampleActivity.java`, the second commit fixes the bug by only collapsing expanded items on the same level as the newly expanded item.
> Fix "only one expanded item" function on multi level hierarchies

- library-core/src/main/java/com/mikepenz/fastadapter/FastAdapter.java
```java
((ExpandableExtension<Item>)fastAdapter.getExtension(ExpandableExtension.class)).getExpandedItems()
```
becomes
```java
fastAdapter.<ExpandableExtension<Item>>getExtension(ExpandableExtension.class).getExpandedItems()
```
with no downside.
> increase type safety and convenience of getExtension

- library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/ActionModeHelper.java
If we just want to use the default implementation of the ActionModeHelper, it is needed a mechanism to expose the click over the cab menu items.
This just provides a new constructor where a listener can be passed on to manage the click without having to create a new actionmodecallback element
> Expose Inner ActionModeCallback click event

- build.gradle
- library-extensions/src/main/java/com/mikepenz/fastadapter_extensions/UndoHelper.java
When items get deleted to fast, they were not removed from the recyclerView, because notifyCommit() was also called on the new inserted history (once to often).
Unwanted sequence:
User calls remove() -> creates History 1 -> call show() Snackbar 1 -> onShown() executes doChange() -> user calls remove() before Snackbar 1 dismissed -> notifyCommit() called for History 1 -> creates new History 2 -> call show() Snackbar 2 -> Snackbar 1 dismissed by consecutive event -> notifyCommit() on History 2 -> Snackbar 2 onShown() -> doChange() is called on null History -> History 2 not removed from recycler view
> Fixed UndoHelper

- app/build.gradle
- app/src/main/java/com/mikepenz/fastadapter/app/ExpandableSampleActivity.java
- app/src/main/java/com/mikepenz/fastadapter/app/IconGridActivity.java
- app/src/main/java/com/mikepenz/fastadapter/app/SampleActivity.java
- app/src/main/java/com/mikepenz/fastadapter/app/items/HeaderSelectionItem.java
- app/src/main/java/com/mikepenz/fastadapter/app/items/IconItem.java
- app/src/main/java/com/mikepenz/fastadapter/app/items/expandable/SimpleSubExpandableItem.java
- app/src/main/java/com/mikepenz/fastadapter/app/items/expandable/SimpleSubItem.java
- build.gradle
- library-core/src/main/java/com/mikepenz/fastadapter/FastAdapter.kt
- library-core/src/main/java/com/mikepenz/fastadapter/IExpandable.kt
- library-core/src/main/java/com/mikepenz/fastadapter/IParentItem.kt
- library-core/src/main/java/com/mikepenz/fastadapter/ISubItem.kt
- library-core/src/main/java/com/mikepenz/fastadapter/adapters/ModelAdapter.kt
- library-core/src/main/java/com/mikepenz/fastadapter/select/SelectExtension.kt
- library-extensions-expandable/src/main/java/com/mikepenz/fastadapter/expandable/ExpandableExtension.kt
- library-extensions-expandable/src/main/java/com/mikepenz/fastadapter/expandable/items/AbstractExpandableItem.kt
- library-extensions-expandable/src/main/java/com/mikepenz/fastadapter/expandable/items/ModelAbstractExpandableItem.kt
- library-extensions-expandable/src/main/java/com/mikepenz/fastadapter/utils/AdapterUtil.java
- library-extensions-expandable/src/test/java/com/mikepenz/fastadapter/ExpandableTestDataGenerator.java
- library-extensions-expandable/src/test/java/com/mikepenz/fastadapter/ExpandableTestItem.java
* do not require a specific VH type for parent and subItem 
* the old definition would require that the VH of parent and subItem is equal
* simplify `IExpandable` introduce `IParentItem`, `ISubItem`..
* the parent for the subitem is this when setting
* release an alpha3 for testing purposes
> [WIP] FastAdapter v4 - Different Expandable approach

- library-core/src/main/java/com/mikepenz/fastadapter/FastAdapter.java
The Java doc was misleading. It is actually required to set withSelectable to true to allow multi selection and by default, no items are selectable.
> Modified Documentation on withSelectable

- library-core/src/main/java/com/mikepenz/fastadapter/adapters/ModelAdapter.kt
- library-extensions-utils/src/main/java/com/mikepenz/fastadapter/adapters/FastItemAdapter.kt
Resolves #776 
You can also open `itemAdapter`, though it leads to the warning of accessing a non final property during `init`. There is already a problem with this through `addAdapter`, which you may want to look into, but that is a separate issue
> Make all FastItemAdapter functions opened

- library-core/src/main/java/com/mikepenz/fastadapter/FastAdapter.kt
- library-core/src/main/java/com/mikepenz/fastadapter/IItemAdapter.kt
- library-core/src/main/java/com/mikepenz/fastadapter/adapters/ModelAdapter.kt
- library-extensions-utils/src/main/java/com/mikepenz/fastadapter/adapters/FastItemAdapter.kt
* use delegation for the `FastItemAdapter` to delegate calls to its `itemAdapter`
* fixes https://github.com/mikepenz/FastAdapter/issues/781
* add missing functions to IItemAdapter interface
@AllanWang
> Use interface and delegation for FastItemAdapter

- library-core/src/main/java/com/mikepenz/fastadapter/FastAdapter.kt
- library-core/src/main/java/com/mikepenz/fastadapter/adapters/ItemAdapter.kt
- library-core/src/main/java/com/mikepenz/fastadapter/adapters/ModelAdapter.kt
- library-core/src/main/java/com/mikepenz/fastadapter/dsl/FastAdapterDsl.kt
- library-core/src/main/java/com/mikepenz/fastadapter/select/SelectExtension.kt
- library-extensions-expandable/src/main/java/com/mikepenz/fastadapter/expandable/ExpandableExtension.kt
* introduce a new proposed DSL to the FastAdapter to simplify setup
The current DSL would look like:
```kotlin
fastadapter<GenericItem> {
selectExtension {
allowDeselection = false
}
expandableExtension {
isOnlyOneExpandedItem = true
}
itemAdapter<GenericItem, SimpleImageItem> {
}
itemAdapter {
}
modelAdapter({ it: Number -> SimpleImageItem() }) {
}
}
fastadapter<SimpleImageItem> {
itemAdapter {
}
}
genericfastadapter {
itemAdapter {
}
}
``` 
Image to see the types resolved:
cc @AllanWang
> DSL for FastAdapter

- library-extensions-diff/src/main/java/com/mikepenz/fastadapter/diff/FastAdapterDiffUtil.kt
(Breaking Change) I think the ones that make sense are where we assign a result, or an item list. Assigning a boolean for `detectMoves` doesn't make sense
> Remove operator functions that don't make as much sense

- build.gradle
- library-core/src/main/java/com/mikepenz/fastadapter/FastAdapter.kt
- library-core/src/main/java/com/mikepenz/fastadapter/adapters/ItemAdapter.kt
- library-core/src/main/java/com/mikepenz/fastadapter/dsl/FastAdapterDsl.kt
- library-core/src/main/java/com/mikepenz/fastadapter/select/SelectExtension.kt
- library-extensions-diff/src/main/java/com/mikepenz/fastadapter/diff/DiffCallbackImpl.kt
- library-extensions-expandable/src/main/java/com/mikepenz/fastadapter/expandable/ExpandableExtension.kt
This PR fixes various concerns as raised:
https://github.com/mikepenz/FastAdapter/issues/801
https://github.com/mikepenz/FastAdapter/issues/805
https://github.com/mikepenz/FastAdapter/issues/806
It also includes some other smaller changes like proper experimental flag usage, and re-add back the DSL marker. 
Also change to use `asSequence` and make those functions return lists instead of an array (no reason why it would require to be an array, also asSequence has no direct asIntArray function)
cc @AllanWang
> Address various concerns

- library-core/src/main/java/com/mikepenz/fastadapter/listeners/OnBindViewHolderListenerImpl.kt
- library-core/src/main/java/com/mikepenz/fastadapter/listeners/OnCreateViewHolderListenerImpl.kt
Currently these classes are final, which breaks objects extending them from previous versions of FastAdapter
> Make OnBindViewHolderListenerImpl and OnCreateViewHolderListenerImpl open

- library-core/src/main/java/com/mikepenz/fastadapter/IItemList.kt
- library-core/src/main/java/com/mikepenz/fastadapter/adapters/ModelAdapter.kt
- library-extensions-paged/src/main/java/com/mikepenz/fastadapter/paged/PagedItemListImpl.kt
- library-extensions-paged/src/main/java/com/mikepenz/fastadapter/paged/PagedModelAdapter.kt
* a PagedListAdapter is allowed to have placeholders. those placeholders are defined as null
* introduce a interceptor to specify what item the adapter should provide if an element is still a placeholder.
* FIX https://github.com/mikepenz/FastAdapter/issues/843
> Fix #843 -> PagedItemList should support placeholders

- library-extensions-swipe/src/main/java/com/mikepenz/fastadapter/swipe/SimpleSwipeCallback.kt
- library-extensions-utils/src/main/java/com/mikepenz/fastadapter/swipe_drag/SimpleSwipeDragCallback.kt
At the moment you must specify a drawable on the `SimpleSwipeCallback` for swipe to be enabled. I have changed this so if either a background colour or a "leave-behind" drawable is set, swipe is enabled.
> Allow swipes without setting "leave-behind" drawables

- library-extensions-binding/src/main/java/com/mikepenz/fastadapter/binding/AbstractBindingItem.kt
Rename parameters in AbstractBindingItem to match the type for the newly added Binding functions.
> Rename parameters in AbstractBindingItem to match the type

- app/src/main/java/com/mikepenz/fastadapter/app/ExpandableSampleActivity.kt
- library-extensions-expandable/src/main/java/com/mikepenz/fastadapter/expandable/ExpandableExtension.kt
#911 Added method for expanding all items on a path. Updated the example just to show how to use this method.
I'm not sure what are use cases of using similar method `expandIncludeParents`. I mean, is there any way to get a position of a collapsed element?
> Add expandAllOnPath method to ExpandableExtension

- app/src/main/java/com/mikepenz/fastadapter/app/SwipeDrawerListActivity.kt
- library-extensions-swipe/src/main/java/com/mikepenz/fastadapter/swipe/SimpleSwipeDrawerCallback.kt
- library-extensions-utils/src/main/java/com/mikepenz/fastadapter/swipe_drag/SimpleSwipeDrawerDragCallback.kt
Add an optional callback interface to `SimpleSwipeDrawerCallback`
- `SimpleSwipeDrawerCallback.ItemSwipeCallback.itemSwiped` : Called when a drawer has been swiped (same bahaviour as `SimpleSwipeCallback.ItemSwipeCallback.itemSwiped`)
- `SimpleSwipeDrawerCallback.ItemSwipeCallback.itemUnswiped` : Called when a drawer has been un-swiped (= returns to its default position)
+ update `SwipeDrawerListActivity` to log these events.
> Swipe events for SwipeDrawer behaviour

- app/build.gradle
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- gradle 6.8.1
- build tools 4.1.2
- material components 1.3.0
- kotlin 1.4.30
- iconics 5.2.5
- update sample app font dependencies
- materialDrawer 8.3.1
- aboutLibs 8.8.1
- roboelectric 4.5.1
- detekt 1.15.0
- room 2.2.6
- include mavenCentral repo
> Kotlin 1.4.30 | Material components 1.3.0 | Gradle 6.8.2

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/mikepenz/fastadapter/app/DragAndDropActivity.kt
- app/src/main/java/com/mikepenz/fastadapter/app/SampleActivity.kt
- app/src/main/java/com/mikepenz/fastadapter/app/items/DraggableSingleLineItem.kt
- app/src/main/java/com/mikepenz/fastadapter/app/items/SectionHeaderItem.kt
- app/src/main/java/com/mikepenz/fastadapter/app/items/SmallIconSingleLineItem.kt
- app/src/main/java/com/mikepenz/fastadapter/app/view/DraggableFrameLayout.kt
- app/src/main/java/com/mikepenz/fastadapter/app/view/RecyclerViewBackgroundDrawable.kt
- app/src/main/res/animator/draggable_state_list_anim.xml
- app/src/main/res/drawable/ic_drag_handle.xml
- app/src/main/res/layout/draggable_single_line_item.xml
- app/src/main/res/layout/section_header_item.xml
- app/src/main/res/layout/small_single_line_item.xml
- app/src/main/res/values-night/colors.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/ids.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
- app/src/main/res/values/themes.xml
- fastadapter-extensions-drag/src/main/java/com/mikepenz/fastadapter/drag/ItemTouchCallback.kt
- fastadapter-extensions-drag/src/main/java/com/mikepenz/fastadapter/drag/SimpleDragCallback.kt
This fixes a couple of issues in `SimpleDragCallback` (see individual commits) and adds a new activity showing off how to reorder (parts of) a list.
https://user-images.githubusercontent.com/218061/111382299-1979b880-86a7-11eb-97fc-7f5886c2f13d.mp4
> Fix drag & drop issues in SimpleDragCallback

- fastadapter/src/main/java/com/mikepenz/fastadapter/FastAdapter.kt
- ensure we compute the correct location in case of more than 2 child adapters
- FIX https://github.com/mikepenz/FastAdapter/issues/988
> Fix wrong position in case of more than 2 child adapters

- .github/workflows/ci.yml
- app/build.gradle
- app/src/main/java/com/mikepenz/fastadapter/app/PagedActivity.kt
- build.gradle
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- update materialdrawer 8.3.2
- ci pipeline java 11
- disable jetifier
- androidx multidex
-  more dependency updates 
- recyclerView 1.2.0
- kotlin 1.4.32
- build tools 4.1.3
- iconics, materialdrawer, aboutlibs, detekt
- lifecycle 2.3.1
-----
Sadly as of the time speaking realm, mopub, ... all still depend on jcenter. re-evaluate at a later point
> Remove library reliance on jcenter | limit sample app repositories

- fastadapter-extensions-expandable/src/main/java/com/mikepenz/fastadapter/expandable/ExpandableExtension.kt
- lower requirement for expandable parent detection to `ISubItem` (a subitem should not be required to be a `IExpandable`)
> Fix `ISubItem`  not allowed to have only 1 item expanded

- fastadapter-extensions-swipe/src/main/java/com/mikepenz/fastadapter/swipe/Extensions.kt
- fastadapter-extensions-swipe/src/main/java/com/mikepenz/fastadapter/swipe/ISwipeable.kt
- fastadapter-extensions-swipe/src/main/java/com/mikepenz/fastadapter/swipe/SimpleSwipeCallback.kt
- fastadapter-extensions-swipe/src/main/java/com/mikepenz/fastadapter/swipe/SimpleSwipeDrawerCallback.kt
should solve https://github.com/mikepenz/FastAdapter/issues/1008
Extension file with ISwipeable extension was created to make the function inside it internal and final (which would not be possible inside the interface itself)
> ISwipeable extended

- fastadapter-extensions-paged/src/main/java/com/mikepenz/fastadapter/paged/PagedItemListImpl.kt
The presence of placeholders isn't something to warn about at every single instanciation
> Change logging level of placeholder interceptor (warning->debug)
